title: ruig tuig
logo: /assets/img/logo.png
description: groeiend sporterscollectief met "Vlaamse Ardennen" & "Pays des Collines" als uitvalsbasis
show_downloads: true
google_analytics:
theme: jekyll-theme-minimal
